name: ld27
description: A sample web application
dependencies:
  browser: any
  canvas_query: any
  dartemis: any
  dartemis_toolbox: any
  simple_audio:
    git: https://github.com/johnmccutchan/simpleaudio.git
  vector_math: any
