name: ld27
description: A sample web application
dependencies:
  browser: any
  dartemis: any
  dartemis_toolbox: any
  simple_audio:
    path: ../simple_audio
  vector_math: any
  dart_to_js_script_rewriter: any
transformers:
- dart_to_js_script_rewriter